version: '3'

volumes:
  motley_cue_sock:

networks:
  my-network:
    driver: bridge

services:
  motley_cue_pam_ssh:
    build:
      context: .
      target: motley_cue_pam_ssh
    hostname: "ssh-host"
    restart: on-failure
    ports:
      - "1022:22"
    networks:
      - my-network
    env_file:
      - .env
    environment:
      - UID
      - GID
      - SHELL
    volumes:
      - ${CONFIG_FOLDER}:/config_files
      - motley_cue_sock:/run/motley_cue
      - ./pam-ssh-oidc-config.ini:/etc/pam.d/pam-ssh-oidc-config.ini

  nginx:
    image: nginx
    hostname: "mc_endpoint"
    expose:
      - 8443
      - 443
      - 80
    ports:
      - "8443:8443"
      - "443:443"
      - "80:80"
    networks:
      - my-network
    volumes:
      - ./nginx.default:/etc/nginx/conf.d/default.conf
      - ./nginx.motley_cue:/etc/nginx/conf.d/motley_cue.conf
      - ./nginx.webssh-oidc:/etc/nginx/conf.d/webssh-oidc.conf
      - ${CONFIG_FOLDER}:/config_files
      - motley_cue_sock:/run/motley_cue
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  webssh-oidc:
    image: ddgu/webssh-oidc
    hostname: "webssh-oidc"
    restart: on-failure
    expose:
      - 8444
    networks:
      - my-network
    env_file:
      - .webssh-oidc.env
    volumes:
      - ${CONFIG_FOLDER}:/app/config
      - ${CONFIG_FOLDER}/docs:/app/build/client/docs

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

