version: '3'

volumes:
  motley_cue_sock:

networks:
  my-network:
    driver: bridge

services:
  motley_cue_pam_ssh:
    build:
      context: .
      target: motley_cue_pam_ssh
    hostname: "ssh-host"
    ports:
      - "1022:22"
    networks:
      - my-network
    env_file:
      - .env
    environment:
      - UID
      - GID
      - SHELL
    volumes:
      - ${CONFIG_FOLDER}:/config_files
      - motley_cue_sock:/run/motley_cue

  nginx:
    image: nginx
    hostname: "mc_endpoint"
    expose:
      - 8080
      - 80
    ports:
      - "8080:8080"
      - "80:80"
    networks:
      - my-network
    volumes:
      - ./nginx.motley_cue:/etc/nginx/conf.d/default.conf
      - ./nginx.webssh-oidc:/etc/nginx/conf.d/webssh-oidc.conf
      - ${CONFIG_FOLDER}:/config_files
      - motley_cue_sock:/run/motley_cue

  webssh-oidc:
    image: ddgu/webssh-oidc
    hostname: "webssh-oidc"
    expose:
      - 8444
    networks:
      - my-network
    env_file:
      - .webssh-oidc.env
    volumes:
      - ${CONFIG_FOLDER}:/app/config
